version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: webapp
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
    ports:
      - "3300:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    image: mcunha08/cinemaapp
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: webapp
      MYSQL_USER: testuser
      MYSQL_PASSWORD: test

volumes:
  mysql_data:
    driver: local
